### ISSUE TITLE
media-plugins/kodi-addon-pvr: Add iptv-simple addon

### ISSUE THREAD

**Issue by pashosh** [frace/kodi-overlay#27] opened 2015-02-10 12:56 UTC
from here:
https://github.com/afedchin/xbmc-addon-iptvsimple

**Comment by frace** [comment] 2015-02-10 13:27
The sources of `media-plugins/kodi-addon-pvr` include an "iptv-simple addon" as far as I can tell. Have a look at the sources here: https://github.com/opdenkamp/xbmc-pvr-addons

You can enable it by `IUSE="iptv"`.

**Comment by pashosh** [comment] 2015-02-10 14:04
where do i add the line: IUSE="iptv" ?

do you mean maybe to add iptv USE flag to media-plugins/kodi-addon-pvr in package.use file?

**Comment by frace** [comment] 2015-02-10 14:09
Exactly:

```
media-plugins/kodi-addon-pvr iptv
```

`IUSE` is the variable name used in ebuilds where all the different USE flags are defined.

**Comment by pashosh** [comment] 2015-02-10 14:17
OK, thank you very much.
i'll report after doing that, if it works or not :-)

**Comment by pashosh** [comment] 2015-02-10 20:57
no, it is not working for me.
i added to package.use this line:
media-plugins/kodi-addon-pvr iptv

when i install the pvr package i eventually get this error:

    Makefile:488: recipe for target 'FilmonAPI.lo' failed
    make[2]: *** [FilmonAPI.lo] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[2]: Leaving directory '/var/tmp/portage/media-plugins/kodi-addon-pvr-14.0_rc3/work/xbmc-    pvr-addons-Helix_rc3/addons/pvr.filmon'
    Makefile:385: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/var/tmp/portage/media-plugins/kodi-addon-pvr-14.0_rc3/work/xbmc-pvr-addons-Helix_rc3/addons'
    Makefile:448: recipe for target 'all-recursive' failed 
    make: *** [all-recursive] Error 1
     * ERROR: media-plugins/kodi-addon-pvr-14.0_rc3::kodi-overlay failed (compile phase):
     *   emake failed
    

if i do not change the package.use, this package installs great, but without the iptv simple addon.


i also looked at the ebuild:
https://github.com/frace/kodi-overlay/blob/master/media-plugins/kodi-addon-pvr/kodi-addon-pvr-14.0_rc3.ebuild

and you can see that it already have in IUSE the 'iptv' word, so it is also very strange.

**Comment by frace** [comment] 2015-02-11 00:39
I can can confirm that both, stable and live ebuilds, do not build successfully. It seem like the filmon add-on is to blame.
The problem is that the package does not allow us to build add-ons conditionally. It's a get all or nothing strategy right now. Enabling `--enable-addons-with-dependencies` builds both, iptv-simple and filmon - but we can't choose them individually.

I need to consider whether or not to write an ebuild for iptv-simple. Honestly I'm tempted to hardmask the current ebuild until the build system of the add-on collection will be refactored upstream.

**Comment by pashosh** [comment] 2015-02-11 10:06
can you please tell me where i need do add: --enable-addons-with-dependencies ?
for the time being, i'll happy to have iptv simple, even if it installs with  filmon :-).

**Comment by pashosh** [comment] 2015-02-11 11:17
when i try to update world, i see that portage want to remerge kodi without the pvr USE flag (-pvr), but when i continue with it, it give me this:
    Calculating dependencies... done!

    >>> Verifying ebuild manifests

    !!! Digest verification failed:
    !!! /var/lib/layman/kodi-overlay/media-tv/kodi/metadata.xml
    !!! Reason: Filesize does not match recorded size
    !!! Got: 1287
    !!! Expected: 1350

so i unmerge kodi completely and try to merge it again, but it give me the same message, and now i can't install kodi :).

**Comment by frace** [comment] 2015-02-11 12:05
> can you please tell me where i need do add: --enable-addons-with-dependencies ?
for the time being, i'll happy to have iptv simple, even if it installs with filmon :-).

As I wrote earlier, we can't have one without another. Since filmon breaks the entire build there's nothing I can do about that at the moment.

> when i try to update world, i see that portage want to remerge kodi without the pvr USE flag (-pvr), but when i continue with it, it give me this:

Fixed with https://github.com/frace/kodi-overlay/commit/33595a81b5ef3cceccf8b9b6c40c56c6b7799d06

**Comment by pashosh** [comment] 2015-02-11 12:39
it installed now.
thank you.

**Comment by frace** [comment] 2015-08-25 16:31
Obsolete, see https://bugs.gentoo.org/show_bug.cgi?id=555792

**Closed by frace** 2015-08-25 16:31 UTC
Labels: new ebuild
